### ISSUE TITLE
Server doesn’t respond to commands

### ISSUE THREAD

**Issue by SwiftCoderJoe** [Phyremaster/papermc-docker#14]
When attached to the server, typing /stop, stop, sending SIGINT does nothing. How can you send server commands?

As an aside, I'm somewhat new to docker so I might be missing something obvious. I'm willing to add/rewrite the README as well.

**Comment by Phyremaster** [comment]
Did you use `-it` when you started the server? If so, can someone else confirm this bug? My professors assigned a ton of homework over Thanksgiving "break," so I'm busy today, and my Docker installation isn't really configured for game servers anyway.

**Comment by SwiftCoderJoe** [comment]
I did not use the -it flag. I'll try that flag at some point, but I've already started using a different distribution of Paper in Docker. However I'd guess if I had used the -it flag it would've worked.

**Comment by SwiftCoderJoe** [comment]
I'm closing this issue as I'm just an idiot and didn't RTFM.

**Comment by Phyremaster** [comment]
You're fine, don't worry about it, it happens to the best of us
