### ISSUE TITLE
ARM64 request

### ISSUE THREAD

**Issue by Area45** [Phyremaster/papermc-docker#15]
I'm not very good when it comes to anything coding. However following a few guides I've gotten your PaperMC-Docker to work on a Raspberry Pi running 64bit Ubuntu Server. I'd like to request having you build using buildX to support ARM through your docker hub and maybe just putting a disclaimer that ARM isn't officially supported. It'd be greatly appreciated as I kinda struggle with having to do that with any update (Especially since PaperMC seems to be making some large changes [apiv2]). However I understand since it's your project and you're doing it for free if you don't want to I'd understand. Thanks for reading my request!

**Comment by Phyremaster** [comment]
I'm not entirely sure how to do this (not very experienced with automatic building/making), but I am totally willing to set it up. As with the update to support Paper's APIv2, this may need to wait until finals are over for the semester (a week or so from now). Any information you could provide in the meantime as to how you've built the image and/or how I should build the image is much appreciated.

**Comment by Phyremaster** [comment]
This should be as simple as changing the base image, which is what I did (in the new branch/tag).

**Comment by Phyremaster** [comment]
Haha sike it doesn't work, there's issues at the first `RUN` line. I'll have to fix this.

**Comment by Area45** [comment]
Hey, I’m sorry I haven’t helped out more. I’ve been super busy and work has been scheduling where I don’t have Internet. 

I might be able to help some this upcoming week. When I completed it last time I followed a guide on docker buildx and ARM. Hopefully I’ll be able to figure out an easy way of doing it again (I forgot how, oops) so I can help out some.

Again I really appreciate you even entertaining the idea of getting it to easily work on arm too.

**Comment by Phyremaster** [comment]
I've tried everything I can think of: separating lines, using semicolons, and changing the line endings to Linux. It still errors out on the `RUN` block. Unless Visual Studio and/or GitHub is just changing stuff (line endings) after I fix it, I have no idea what could possibly be causing this. The base image uses `apt-get`, so it's definitely available as a command. Same with `rm` and presumably `mkdir`. The commands are definitely written correctly, because they work just fine in the master branch. This doesn't make any sense.

**Comment by Area45** [comment]
Hey I’m sorry, life’s hit hard recently and have had some computer trouble. If you’d like you can close this issue and I’ll play around till I can find a way to automate it/ easy walkthrough. Thanks for giving it time and putting a lot of work into it.

**Comment by Phyremaster** [comment]
Hey you're fine, no worries, I wasn't expecting you to fix this for me. No reason to close the issue, it'll just sit until it's solved.

**Comment by rednaz1337** [comment]
I'm running this on a Raspberry Pi 4 with Ubuntu 64 bit. I simply cloned the repo, ran `docker build .` and started the container. This works fine for me.

**Comment by Phyremaster** [comment]
Weird. I've been going off of Docker Hub's auto-building, so there must be an bug in that. It seems like there may be a way to tell Docker Hub to build it properly by adding/editing files in this repo. I'll look into it.

**Comment by Phyremaster** [comment]
I think we need something like what they talk about here: https://github.com/docker/hub-feedback/issues/1261

**Comment by Phyremaster** [comment]
By the way, if cloning from GitHub, building, and then running works, then this issue has been solved. I am going to leave this open, though, to solve the new issue of getting Docker Hub to build the image, as many users would likely prefer to only use Docker Hub.

**Comment by Area45** [comment]
I’m not familiar with docker hub auto building. And I could clone the source and build it on my raspberry pi (I don’t know why I didn’t consider this). I was originally asking to build it slightly differently in docker so others using raspberry pis can just download it from Docker Hub and run it. 

The way I had achieved this on an x86 platform was by downloading the source code and using test version of docker and use docker buildx to create both x86 and arm64 at the same time. I was pretty confused and didn’t fully understand how I reached a working version but I just followed a guide on docker buildx. Hopefully there’s an easy way to use docker hubs auto-build feature like you mentioned. 

I was planning on being able to help out and walkthrough the process however I wasn’t able to become familiar with it before needing to return a laptop and get a different one due to some issues I was having so now I’m in between computers and in the middle of a move.

I feel bad asking for the comparability now that I’m not able to help as much but I’ll be getting a new computer soon. I really appreciate the effort you’ve gone through and done for this @Phyremaster

**Comment by Phyremaster** [comment]
Don't feel bad, I appreciate suggestions for improvements. It really hasn't been that much trouble, I just haven't been able to put much time into getting this figured out.

**Comment by Area45** [comment]
I was able to get it to work through an action on GitHub. 
<a href=https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/master/.github/workflows/docker-multiarch-publish.yml>Original post</a>

I then edited it slightly to get it to work on my forked version of your papermc-docker. <a href='https://github.com/Area45/papermc-docker/blob/master/.github/workflows/docker-multiarch-publish.yml'>Here</a> is mine. And <a href='https://hub.docker.com/repository/docker/sassychan/papermcarm64/tags?page=1&ordering=last_updated'>here</a> is my docker hub tags to show it's working.
If you modify the `on:` section using <a href='https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run'>Events that trigger workflows</a> then you should be able to get it to run when you want it to.

I'm still very new to GitHub and docker but let me know if I can help at all! (Or explain anything better)
I want to remind you I don't expect you to go out of your way to get it working on arm. I made a program to pull and build it on an arm machine then push it to docker hub like what was suggested above, But I'd still love an easy way to keep it automatically up to date with your version.

**Comment by Phyremaster** [comment]
I'll be honest, I don't entirely know how GitHub actions work. Would this build the image and push it to Docker Hub every time the branch gets a new commit? Would it run on GitHub's infrastructure? Do they eventually start charging for that? I intend to do some work on my own infrastructure this summer, so I may eventually be able to host the automation stuff myself if necessary. If I can just drop this in and have GitHub do the work, though, that's great and I'll do it.

**Comment by Phyremaster** [comment]
Wait, there can be images for multiple architectures under the same tag? I had no idea! Wow, that makes this way simpler...

**Comment by Phyremaster** [comment]
Oh, it looks like this can just be merged in (as long as I get the secrets set up on this repository first). Nice! And the other tags (older JDKs) should only need small tweaks. Go ahead and create a PR, I'll merge it tonight if I can.

**Comment by Phyremaster** [comment]
Does it work without the `package-version` step? I think that's for NPM, which shouldn't be used because Node.js isn't involved here.

**Comment by Area45** [comment]
It looks like GitHub gives free users 2,000 action minutes per month which should be more than plenty as I think this doesn't take more than one per run. Checking my account after running it a few times it still shows 0 minutes but for private repositories (So maybe is completely free or just free because it's easy for the server?). It can't charge you unless you add a payment method though. Originally I was running docker buildx and was going to try and make a program to build multi arch images with it, but I think this way is better/easier.

How I have the action setup now it only runs if you manually tell it to under the action tab. However there are ways to setup to make it automatic based on triggers in GitHub and is listed on <a href='https://docs.github.com/en/actions/reference/events-that-trigger-workflows'>this page</a>. I'm not too familiar with how GitHub functions or terminology otherwise I'd help set it up better. 

Currently it'll build for both arm64 and amd64 with the tag of latest.

I'll submit a Pull Request, I have it set so it just shows the one file being changed but I had touched a few things in attempts to make the actions work until I figured it out. I reverted all of them so just the one is added/changed. If you have any questions let me know.

**Comment by Phyremaster** [comment]
Alright, Docker Hub shows both architectures for all tags now.

**Comment by Area45** [comment]
No problem, I had a working version of an arm build but I’m really excited it’ll be automatically built now! Thanks so much for working on this with means being so open to it!

**Comment by Phyremaster** [comment]
No problem. After all, you did most of the issue-solving.
