### ISSUE TITLE
jdk8 - papermc 1.8.8

### ISSUE THREAD

**Issue by rares1337** [Phyremaster/papermc-docker#20]
hello, i would like to use jdk 8 for my papermc server
can you help me?
thanks in advance

**Comment by Phyremaster** [comment]
Ok, gimme a minute, this should be as simple as creating a couple new branches/tags

**Comment by Phyremaster** [comment]
@rares1337 Confirmed available on Docker Hub with tag `openjdk8`. Have fun gaming!
