### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by StelFux** [Phyremaster/papermc-docker#31]
Hello,
In this repository, there is no license, even for the start-up script.
I think the MIT license is the most appropriate here.
Would it be to add one?

**Comment by Phyremaster** [comment]
This has been suggested before. I like to avoid legalese if at all possible. I'll look into licenses like the MIT license and Creative Commons licenses at some point and if I find one I like for this I'll add it. I might actually be locked into a specific license by PaperMC and/or Minecraft. For now, no license. I don't care how anyone uses this so long as they aren't violating PaperMC or Mojang licenses/TOS/etc.
