### ISSUE TITLE
Upgrade to Java 16 for Minecraft version 1.17+

### ISSUE THREAD

**Issue by baxzzi** [Phyremaster/papermc-docker#34]
The issue is that I am trying to figure out how to upgrade the docker to use Java 16 instead Java 11.

I am trying to figure this out especially since this notice appears in console on startup:

> [Thu, 13. May 2021 01:24:14 UTC WARN] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
[Thu, 13. May 2021 01:24:14 UTC WARN] \* WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[Thu, 13. May 2021 01:24:14 UTC WARN] \* PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[Thu, 13. May 2021 01:24:14 UTC WARN] \* JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[Thu, 13. May 2021 01:24:14 UTC WARN] \*
[Thu, 13. May 2021 01:24:14 UTC WARN] \* Please update the version of Java you use to run Paper
[Thu, 13. May 2021 01:24:14 UTC WARN] \* to at least Java 16. When Paper for Minecraft 1.17 is
[Thu, 13. May 2021 01:24:14 UTC WARN] \* released support for versions of Java before 16 will
[Thu, 13. May 2021 01:24:14 UTC WARN] \* be dropped.
[Thu, 13. May 2021 01:24:14 UTC WARN] \*
[Thu, 13. May 2021 01:24:14 UTC WARN] \* Current Java version: 11.0.10
[Thu, 13. May 2021 01:24:14 UTC WARN] \*
[Thu, 13. May 2021 01:24:14 UTC WARN] \* Check this forum post for more information:
[Thu, 13. May 2021 01:24:14 UTC WARN] \*   https://papermc.io/java16
[Thu, 13. May 2021 01:24:14 UTC WARN] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*

The image attached is how I currently have it setup, yet it seems to want to default to Java 11.

![Capture](https://user-images.githubusercontent.com/68846447/118064405-c8f1a500-b34f-11eb-839e-f59d11d2a10a.PNG)

**Comment by Phyremaster** [comment]
Yeah, this change will be necessary for Minecraft versions 1.17 and beyond. I'll make a branch and tag for Java 11 and update the main branch to Java 16. For now, unless you're running a snapshot server, you can safely ignoring that series of warning messages.

**Comment by baxzzi** [comment]
Thank you very much!

**Comment by Phyremaster** [comment]
This still needs to be fixed, it's just not urgent because it doesn't affect the current release of the game.

**Comment by Timi7007** [comment]
According to [the paper website](https://papermc.io/forums/t/java-16-mc-1-17-and-paper/5615) they initially planned upgrading to 11, but Mojang decided to go with 16 in snapshot 21w19a.
Java 16 is NOT an LTS version, 17 will be the next. Previews of Java 17 are available, but incompatible with Minecraft as of now:
```
2021-05-18 19:20:43 (17.3 MB/s) - ‘papermc-1.16.5-703.jar’ saved [53710637/53710637]
Downloading vanilla jar...
Patching vanilla jar...
Unsupported Java detected (61.0). Only up to Java 16 is supported.
```
