### ISSUE TITLE
[Suggestion] Set PUID and PGID.

### ISSUE THREAD

**Issue by vincentchu37** [Phyremaster/papermc-docker#5]
It would be cool if we could set PUID and PGID in the docker container so everything isn't created as root into my local filesystem. 

Thanks for your image!

**Comment by Phyremaster** [comment]
I haven't tested it myself, but I think you should be able to simply use Docker's `--user` option to run the container as whatever user and group you want to without issues from the image. Nothing that the container would do relies on `$HOME` or the current user's username, as far as I am aware.

**Comment by vincentchu37** [comment]
Just tested, so far so good! Thanks!
