### ISSUE TITLE
Can this run on ARMv7 32bit architecture?

### ISSUE THREAD

**Issue by Suffice** [Phyremaster/papermc-docker#50]
I tried running the given command:
`sudo docker run -p 25565:25565 phyremaster/papermc`
and I get this from the console:
```
/storage/.kodi/userdata/addon_data/mtoensing-Docker-Minecraft-PaperMC-Server-33c7ca5$ docker run -p 25565:25565 phyremaster/papermc
Unable to find image 'phyremaster/papermc:latest' locally
latest: Pulling from phyremaster/papermc
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
```
Does this Docker container currently work with ARM 32bit architecture? 

This is my first time trying to install a docker container not included with LibreELEC, so I'm not really sure if this can work with my system.

**Comment by Phyremaster** [comment]
This is not currently auto-built for ARM, just ARM64. In theory, it should be an easy addition, unless this images uses something that's 64-bit only.

**Comment by Area45** [comment]
I attempted this however it looks like openjdk doesn't have an ARMv7 build so I'm not sure this is possible. If you're running it off a raspberry pi 3 or 4 then I'd suggest installig ubuntu server 64bit if possible.

**Comment by Suffice** [comment]
I ended up going with the itzg / docker-minecraft-server build

It lets you specify which version of Java you want to run, and what type of server jar file use. 

Hotspot Java 16 works with AMD64, ARM64, ARMv7.
