### ISSUE TITLE
Make "latest" option not case sensitive

### ISSUE THREAD

**Issue by f3rr311** [Phyremaster/papermc-docker#51]
When adding to the env in the container you get 

It seems a extra - appears where it should not be

PAPER_BUILD |                                       1.17.1-133

./papermc.sh: 8: [: =: unexpected operator
--2021-07-28 01:59:20--  https://papermc.io/api/v2/projects/paper/versions//builds/1.17.1-133/downloads/paper--1.17.1-133.jar
Resolving papermc.io (papermc.io)... 104.26.13.138, 172.67.72.198, 104.26.12.138, ...
Connecting to papermc.io (papermc.io)|104.26.13.138|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-28 01:59:21 ERROR 404: Not Found.

Error: Invalid or corrupt jarfile paper--1.17.1-133.jar

**Comment by f3rr311** [comment]
Ok, I stand corrected, I don't thing the documentation stated that you MUST fill both out or it will not work clearly stated moth must be done when changing these

**Comment by Phyremaster** [comment]
The Minecraft version and Paper build go in separate environment variables (`MC_VERSION` and `PAPER_BUILD`), respectively. You appear to have set `MC_VERSION` to an empty string and `PAPER_BUILD` to the combined version and build. The reason that I conclude that `MC_VERSION` was specifically set to an empty string is that when not included at all, it should default to "latest" and use the latest version at runtime. I see that you have noticed part of the issue while I was replying; I'll go ahead and close this.

**Comment by f3rr311** [comment]
So the error was I set paper as 113 and left MC_Version Blank, Both absolutely have to have something in there or it will not launch


JAVA_HOME	/usr/local/openjdk-16
JAVA_OPTS	
JAVA_VERSION	16.0.1
LANG	C.UTF-8
MC_RAM	10G
MC_VERSION	1.17.1
PAPER_BUILD	133
PATH	/usr/local/openjdk-16/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

 what finally made it launch was adding MC version 1.17.1 as you can see here

**Comment by f3rr311** [comment]
> The Minecraft version and Paper build go in separate environment variables (`MC_VERSION` and `PAPER_BUILD`, respectively). You appear to have set `MC_VERSION` to an empty string and `PAPER_BUILD` to the combined version and build. The reason that I conclude that `MC_VERSION` was specifically set to an empty string is that when not included at all, it should default to "latest" and use the latest version at runtime. I see that you have noticed part of the issue while I was replying; I'll go ahead and close this.

This is not right leaving it blank does not make it goto the latest version, it fails to launch.

**Comment by Phyremaster** [comment]
"Leaving the other empty" is setting it to an empty string. To not specify it, it has to be left out completely. Looking at the variables you posted, though, I'm assuming you're using some form of 3rd party management software, such as Portainer; since leaving an environment variable out isn't usually an option on these platforms, you should leave it at the auto-filled default ("latest") or change it to a value of your choice, not set it to an empty string.

**Comment by f3rr311** [comment]
Yeah, using portainer to manage it, got me there. :) 

![image](https://user-images.githubusercontent.com/14023914/127256488-7d5ea5f4-ae18-48fa-935b-671117dcedb0.png)
If you edit the env's like this it won't default to latest in there. Other than this tiny bump AMAZING work on this thank you :)

**Comment by Phyremaster** [comment]
Huh, interesting. I assumed it would fill in the defaults since it did so for the Java EVs. Not much I can do here, but I'll edit the README to mention this.

(P.S.: At this point, I'd bet the majority of code in this repo isn't even my work lol)

**Comment by f3rr311** [comment]
The issue I had noticed was if you set MC version to 1.17.1 and the other to latest, it just added latest to the URL to get the download and messed up for me at least.

**Comment by Phyremaster** [comment]
Wait, that's supposed to work. If it doesn't, that's an actual issue. It might have broken due to changes in the Paper API.

**Comment by f3rr311** [comment]
Well I feel like a idiot now, its case sensitive I don't know why I thought it didn't matter lol Linux is so picky sometimes.

I think you can close this and chalk it up as me being dumb.


--2021-07-28 03:09:24--  https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/LATEST/downloads/paper-1.17.1-LATEST.jar

Resolving papermc.io (papermc.io)... 104.26.13.138, 172.67.72.198, 104.26.12.138, ...

Connecting to papermc.io (papermc.io)|104.26.13.138|:443... connected.

HTTP request sent, awaiting response... 404 Not Found

2021-07-28 03:09:25 ERROR 404: Not Found.

**Comment by Phyremaster** [comment]
Ah, gotcha. I can actually make this not case sensitive, I think, so I'll turn this issue into an improvement request for that.
