### ISSUE TITLE
IP-Address 

### ISSUE THREAD

**Issue by maaanuuuuu** [Phyremaster/papermc-docker#52]
Hello, I checked the ip address from joining users and the address is the ip address from the docker-gateway.
`172.17.0.1`

I am new to docker, so maybe is my config wrong, does anyone know a fix for this?

Thanks

**Comment by Phyremaster** [comment]
I'm afraid I don't understand what the issue is. Are these users not able to connect to the server?

**Comment by maaanuuuuu** [comment]
No they can, but I don't get their real IP address, docker's proxy hides them.

**Comment by Phyremaster** [comment]
> docker's proxy
Not an issue here then, please go ask the Docker people how this works.
