### ISSUE TITLE
Bug in exposed ports

### ISSUE THREAD

**Issue by DanielSchetritt** [Phyremaster/papermc-docker#55]
# Summary
The current `Dockerfile` is not correctly exposing the ports/protocols.

## Minecraft Port

Minecraft Java Edition only needs `25565/tcp` and not UDP. Bedrock Edition requires UDP instead of TCP.
Citation: see the table under step 7 of [this section of Microsoft's documentation](https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/multiplayer-basic-game-server-hosting#set-up-an-azure-virtual-machine-attach-a-persistent-disk-and-open-ports).

I don't think PaperMC supports Bedrock Edition, so we can safely remove `EXPOSE 25565/udp` from the [`Dockerfile`](https://github.com/Phyremaster/papermc-docker/blob/fbab452bc13ed9e0f95b28f836874e52d895b582/Dockerfile#L22). It probably wouldn't hurt to leave it exposed since its inside a container, but it would probably be better to remove it for not being used.

## Remote Console Port
In [`README.md`](https://github.com/Phyremaster/papermc-docker/blame/master/README.md#L21), there is an example for mapping the RCON port to the container's port `25575/tcp`. However this port is not exposed in the `Dockerfile`.
To allow RCON to work, `EXPOSE 25575/tcp` should be added to the `Dockerfile`.

**Comment by Phyremaster** [comment]
While the gameplay connection occurs exclusively over TCP, [the query protocol that Minecraft uses](https://wiki.vg/Query) (which supplies information like the playercount and MOTD to the client for display in the server list) uses UDP, with a default port of 25565.

The RCON port is a deliberate omission from the exposed ports. Many users will not use RCON, and forcing them to expose the port poses a security risk, albeit a very slight one. This omission has no effect on the steps the user must take to set up RCON.

**Comment by DanielSchetritt** [comment]
Ah I see. Thank you for telling me about the use of UDP on port 25565. If RCON's port is not exposed, how can it be set up?

**Comment by Phyremaster** [comment]
I had read previously that all `EXPOSE`d ports had to be published with `-p`, but apparently this is not the case (anymore?). The Docker documentation is not very clear about what the `EXPOSE` directive actually _does_. The only notable thing it mentions is that [the `-P` option publishes all `EXPOSE`d ports](https://docs.docker.com/engine/reference/run/#expose-incoming-ports); some users (e.g. server hosts) might like to use this option without automatically publishing the RCON port (which can be added back in with `--expose`, it seems).

Additionally, other (admittedly questionable) sources on the web say that `EXPOSE` still exposes the ports... internally? I thought other containers within the same virtual network were just always allowed to communicate on all ports though.
