### ISSUE TITLE
"Permission denied" error from container

### ISSUE THREAD

**Issue by ajsirota** [Phyremaster/papermc-docker#79]
Here's what I'm doing:
```
[opc@instance-20241111-1030 eamc]$ sudo docker run -p 25565:25565 -e EULA="true" -v /srv/eamc/storage:/papermc:rw -it phyremaster/papermc
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
paper-1.21.3-26.jar: Permission denied
./papermc.sh: line 40: eula.txt: Permission denied
Error: Unable to access jarfile paper-1.21.3-26.jar
```

I'm on Oracle Linux 8. I'm using Podman emulating Docker, but I heavily doubt that would be causing this.

**Comment by Phyremaster** [comment]
This isn't specific to this image, but rather a common issue with filesystem permissions for containers. My advice would be to check the permissions on your volume mountpoint and go from there.
